version: '3'

networks:
    urlwatch:

services:
  urlwatch:
    build:
      context: .
    volumes:
      - ./data:/data/urlwatch
      - /etc/localtime:/etc/localtime:ro
    restart: "unless-stopped"
    networks:
      - urlwatch
